In [37]:
from google.colab import files

files.upload()

{}

In [2]:
!kaggle datasets download -d daniaherzalla/tii-ssrc-23


Dataset URL: https://www.kaggle.com/datasets/daniaherzalla/tii-ssrc-23
License(s): CC-BY-SA-4.0
100% 3.10G/3.10G [00:28<00:00, 117MB/s] 



In [3]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
df = pd.read_csv('/content/csv/data.csv')

In [7]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df['hour'] = df['Timestamp'].dt.hour
df['day'] = df['Timestamp'].dt.day
df['weekday'] = df['Timestamp'].dt.weekday

In [8]:
drop_col = ["Flow ID" , "Src IP"  ,"Dst IP" , "Timestamp"]
df =df.drop(drop_col , axis=1)

In [9]:
cat_col = df.select_dtypes(include="object").columns


In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in cat_col:
    df[col] = le.fit_transform(df[col])

In [11]:
y_label = df['Label']
X = df.drop(['Label',"Traffic Type" , "Traffic Subtype"], axis=1)

In [12]:
y_Traffic_Type = df['Traffic Type']
y_Traffic_subtype = df['Traffic Subtype' ]


In [13]:
from sklearn.preprocessing import StandardScaler

# scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [28]:
y_label.value_counts()

,count
Label,
1,8655466
0,1301


In [19]:
import keras

model = keras.models.load_model("my_model.keras")

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 16 variables whereas the saved optimizer has 30 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [21]:
y_pred_label_, y_pred_type_, y_pred_subtype_ = model.predict(X_scaled)

270524/270524 ━━━━━━━━━━━━━━━━━━━━ 203s 750us/step


In [33]:
import numpy as np

# label binary
y_pred_label_class_ = (y_pred_label_ > 0.6).astype(int)

# Traffic Type
y_pred_type_class_= np.argmax(y_pred_type_, axis=1)

# Traffic Subtype
y_pred_subtype_class_ = np.argmax(y_pred_subtype_, axis=1)

In [36]:
from sklearn.metrics import confusion_matrix, classification_report

# label
print(confusion_matrix(y_label, y_pred_label_class_))
print(classification_report(y_label, y_pred_label_class_))

# Traffic Type
print(confusion_matrix(y_Traffic_Type, y_pred_type_class_))
print(classification_report(y_Traffic_Type, y_pred_type_class_))

# Traffic Subtype
print(confusion_matrix(y_Traffic_subtype, y_pred_subtype_class_))
print(classification_report(y_Traffic_subtype, y_pred_subtype_class_))

[[   1048     253]
 [    164 8655302]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83      1301
           1       1.00      1.00      1.00   8655466

    accuracy                           1.00   8656767
   macro avg       0.93      0.90      0.92   8656767
weighted avg       1.00      1.00      1.00   8656767

[[      0       0       5      44       0       0       0     141]
 [      0       0       2       2       1       0       0      27]
 [      0       0   34951     170      10       5       0      36]
 [      0       0      86 7490759      21      12       0      51]
 [      0       0      44      44 1038223       0       0      52]
 [      0       0      11      17       3   90937       0      34]
 [      0       0      13      15       0       0       0     181]
 [      0       0      19      82      24       0       0     745]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       190
           1       0.00      0.00      0.00        32
           2       0.99      0.99      0.99     35172
           3       1.00      1.00      1.00   7490929
           4       1.00      1.00      1.00   1038363
           5       1.00      1.00      1.00     91002
           6       0.00      0.00      0.00       209
           7       0.59      0.86      0.70       870

    accuracy                           1.00   8656767
   macro avg       0.57      0.61      0.59   8656767
weighted avg       1.00      1.00      1.00   8656767

[[   10     0     0 ...   130     3     0]
 [    0     0     0 ...    27     0     0]
 [    0     0 22176 ...     0     0     0]
 ...
 [    1     0     0 ...   275    35     0]
 [    0     0     0 ...    28   316     0]
 [    0     0     0 ...    29   112     0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       0.71      0.05      0.10       190
           1       0.00      0.00      0.00        32
           2       1.00      1.00      1.00     22179
           3       1.00      0.99      0.99      3485
           4       0.97      0.95      0.96       628
           5       0.94      0.98      0.96      3967
           6       1.00      0.95      0.97      4913
           7       1.00      1.00      1.00    936307
           8       1.00      1.00      1.00    872523
           9       1.00      1.00      1.00    871150
          10       1.00      1.00      1.00    725600
          11       1.00      1.00      1.00     82351
          12       0.00      0.00      0.00         9
          13       0.00      0.00      0.00        30
          14       1.00      1.00      1.00    909507
          15       1.00      1.00      1.00   1072504
          16       1.00      1.00      1.00    856764
          17       1.00    

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
